library(plotly)
library(shiny)
library(ggplot2)

################################################################################
########### Samplemeta #########################################################
################################################################################

tab_samplemeta <- fluidPage(
  selectInput(
    inputId = "samplemeta_pool",
    label = "Pool:",
    selectize = FALSE,
    multiple = FALSE,
    choices = names(all_samplemeta), 
    selected = names(all_samplemeta)[1]
  ),

  plotOutput(outputId = "plotSamplemetaUmap", height = "700px")
)


################################################################################
########### Gene viewer ########################################################
################################################################################

tab_grstats <- fluidPage(
  column(6,
    wellPanel(
      
      plotlyOutput("plot_grstats_volcano", height = "400px"),
      
      #div(class = "label-left",
          
        selectInput(
          inputId = "grstats_pool",
          label = "Pool:",
          selectize = FALSE,
          multiple = FALSE,
          choices = names(all_grstats), 
          selected = names(all_grstats)[1]
        ),
        
        p(
          "When clicking on a gene in the composite viewer, the relative abundance graphs will be shown for the pool selected above"
        ),

      
      
        selectInput(
          inputId = "grstats_y",
          label = "Y-axis:",
          selectize = FALSE,
          multiple = FALSE,
          choices = c("1/s.d.","-Log10 p, different from control genes"), 
          selected = NULL
        ),
        checkboxInput(
          inputId = "grstats_show_gene_name",
          label = "Show gene name",
          value = FALSE
        ),

        
      plotlyOutput("plot_grstats_composite", height = "400px"),
      
      p(
        "Logistic regression model from screen of 48X and 96X KO screens to determine phenotypes of unstudied genes (in grey). To view relative abundances (panel top right) by clicking on a gene in the composite viewer, first selected 48x or 96x pool above."
      )
      



    )
  ),
  column(6,
     wellPanel(
       
       ########### Top right
       ########### Top right
       ########### Top right
       
       plotlyOutput("plot_grstats_tcplot", height = "400px"),
       
       
       
       selectInput(
         inputId = "grstats_gene",
         label = "Gene:",
         selectize = TRUE,
         multiple = FALSE,
         choices = c(""), 
         selected = NULL
       ),
       
       checkboxInput(
         inputId = "grstats_avg_mouse",
         label = "Average across mice",
         value = TRUE
       ),
       
       checkboxInput(
         inputId = "grstats_avg_grna",
         label = "Average across sgRNAs",
         value = TRUE
       ),
       
       
       selectInput(
         inputId = "grstats_colorby",
         label = "Color by:",
         multiple = FALSE,
         choices = c("Gene","Mouse"
                     #,"Genotype","Treatment","Genotype+Treatment","Genotype+Treatment+Genetic construct"
                     ), 
         selected = c("Gene")
       ),
       
       selectInput(
         inputId = "grstats_units",
         label = "Units:",
         multiple = FALSE,
         selectize = TRUE,
         choices = c("Count/AllCount","Count/ControlCount"), 
         selected = c("Count/AllCount")
       ),
       
       
     )
  ),
)

################################################################################
########### About page #########################################################
################################################################################

tab_about <- fluidPage(
  h1(
    "About"
  ),
  p(
    "This is an interactive Shiny-based app that visualises the analysed data for CRISPR screens using the PbHiT system in the rodent malaria parasite Plasmodium berghei as described in Jonsdottir et al. ",
    "DOI: ", tags$a(href="https://doi.org/10.1101/2024.04.20.590404", "https://doi.org/10.1101/2024.04.20.590404")  
  ),
  p(
    "Generated by the Bushell lab at Umeå University.", tags$a(href="http://www.bushelllab.com/", "http://www.bushelllab.com/")
  )
)




################################################################################
########### Total page #########################################################
################################################################################

#https://stackoverflow.com/questions/72040479/how-to-position-label-beside-slider-in-r-shiny


ui <- fluidPage(

  tags$style(HTML(
    "
    .label-left .form-group {
      display: flex;              /* Use flexbox for positioning children */
      flex-direction: row;        /* Place children on a row (default) */
      width: 100%;                /* Set width for container */
      max-width: 400px;
    }

    .label-left label {
      margin-right: 2rem;         /* Add spacing between label and slider */
      align-self: center;         /* Vertical align in center of row */
      text-align: right;
      flex-basis: 100px;          /* Target width for label */
    }

    .label-left .irs {
      flex-basis: 300px;          /* Target width for slider */
    }
    "
  )),
  shinyjs::useShinyjs(),
  
  
  
  titlePanel(div("Bushell lab, PbHiT CRISPR KO screen in", em("Plasmodium berghei"))),
  
  tabsetPanel(type = "tabs",
              tabPanel("Gene RGRs", tab_grstats),
              #tabPanel("Pool overviews", tab_samplemeta),
              tabPanel("About", tab_about),
  )
  
)



